server:
  port: 8080

spring:
  application:
    name: civa
  datasource:
    url: jdbc:postgresql://localhost:5432/busesdb?serverTimezone=UTC
    username: postgres
    password: sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC